apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
spec:
  tls:
    - hosts:
        - multitracklistening.net
      secretName: multi-track-listening-web-tls
  backend:
    serviceName: web
    servicePort: 8080
